server:
  port: 8085
 
spring:
  profiles: dev
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
        url: jdbc:mariadb://localhost:3306/test
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
        
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
      